name: Deploy on DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Check version
      run: mvn -version
    - name: Verify with Maven
      run: mvn verify
    - name: show event
      run: |
        echo "Tag name : $${{ github.event.release.tag_name }}"
        echo "ref name : $${{ github.event.ref_name }}"
        echo "Event name : ${{github.event_name}}"
        echo "Ref type : ${{github.ref_type}}"
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push arc-web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/app-web.Dockerfile
          tags: 'inseefr/arc:latest'
      - name: Push arc-ws to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./docker/app-ws.Dockerfile
          tags: 'inseefr/arc-ws:latest'
      - name: Push arc-batch to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./docker/app-batch.Dockerfile
          tags: 'inseefr/arc-ws:latest'
