name: Deploy on DockerHub

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify with Maven
      run: mvn verify
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'release'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if .git exists
        run: ls .git
      - name: Push arc-web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./app.Dockerfile
          tags: |
            ${{ github.event_name == 'release' && format('inseefr/arc:{0}', github.event.release.tag_name) || '' }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/arc:latest' || '' }}
      - name: Push arc-ws to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./app-ws.Dockerfile
          tags: |
            ${{ github.event_name == 'release' && format('inseefr/arc-ws:{0}', github.event.release.tag_name) || '' }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/arc-ws:latest' || '' }}
