name: Deploy on DockerHub

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Check version
      run: mvn -version
    - name: Verify with Maven
      run: mvn verify
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'release'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: show event
        run: |
          echo "Tag name : ${{github.ref_name}}"
          echo "Event name : ${{github.event_name}}"
          echo "Ref type : ${{github.ref_type}}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push arc-web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./app-web.Dockerfile
          tags: |
            ${{ github.ref_type == 'tag' && format('inseefr/arc:{0}', github.ref_name) || '' }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/arc:latest' || '' }}
      - name: Push arc-ws to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./app-ws.Dockerfile
          tags: |
            ${{ github.event_name == 'tag' && format('inseefr/arc-ws:{0}', github.ref_name) || '' }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/arc-ws:latest' || '' }}
      - name: Push arc-batch to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./app-batch.Dockerfile
          tags: |
            ${{ github.event_name == 'tag' && format('inseefr/arc-batch:{0}', github.ref_name) || '' }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/arc-batch:latest' || '' }}
