name: release-on-tag

on:
  push:
   tags:
     - version-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: show event
      run: |
        echo "Tag name : $${{ github.event.release.tag_name }}"
        echo "ref name : $${{github.ref_name}}"
        echo "Event name : ${{github.event_name}}"
        echo "Ref type : ${{github.ref_type}}"
    - name: Split branch name
      env:
        BRANCH: ${{ github.ref_name }}
      id: split
      run: echo "fragment=${BRANCH##*-}" >> "$GITHUB_OUTPUT"
    - name: Test variable
      run: |
        echo ${{ steps.split.outputs.fragment }}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Package with Maven
      run: mvn package
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*/target/*.war,arc-batch/target/ArcMain.jar"
        body: "New automated release. See [CHANGELOG](https://github.com/InseeFr/ARC/blob/master/CHANGELOG.md)"
        token: ${{ secrets.GITHUB_TOKEN }}
  push_to_registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push arc-web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/app-web.Dockerfile
          tags: 'inseefr/arc:${{ steps.split.outputs.fragment }}'
      - name: Push arc-ws to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./docker/app-ws.Dockerfile
          tags: 'inseefr/arc-ws:${{ steps.split.outputs.fragment }}'
      - name: Push arc-batch to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true          
          context: .
          file: ./docker/app-batch.Dockerfile
          tags: 'inseefr/arc-ws:${{ steps.split.outputs.fragment }}'